export const ColumnType = {
  Char: "Char",
  CharN: "CharN",
  VarcharN: "VarcharN",
  Text: "Text",
  TinyText: "Tinytext",
  Mediumtext: "Mediumtext",
  Longtext: "Longtext",
  Int: "Int",
  IntN: "IntN",
  TinyInt: "TinyInt",
  TinyIntN: "TinyIntN",
  SmallInt: "SmallInt",
  SmallIntN: "SmallIntN",
  MediumInt: "MediumInt",
  MediumIntN: "MediumIntN",
  BigInt: "Bigint",
  BigIntN: "BigintN",
  Date: "Date",
  Datetime: "Datetime",
  Boolean: "Boolean",
  Binary: "Binary",
  BinaryN: "BinaryN",
  VarbinaryN: "VarbinaryN",
  Bit1: "Bit1",
  BitN: "BitN",
  Blob: "Blob",
  Tinyblog: "Tinyblog",
  Mediumblog: "Mediumblog",
  Longblog: "Longblog",
  Decimal: "Decimal",
  DecimalP: "DecimalP",
  DecimalPS: "DecimalPS",
  Decimal104: "Decimal104",
  Decimal194: "Decimal194",
  Double: "Double",
  DoubleMD: "DoubleMD",
  Enum: "Enum",
  Float: "Float",
  FloatMD: "FloatMD",
  FloatP: "FloatP",
  Geometry: "Geometry",
  Json: "Json",
  Numeric: "Numeric",
  NumericP: "NumericP",
  NumericPS: "NumericPS",
  Real: "Real",
  RealMD: "RealMD",
  Set: "Set",
  Time: "Time",
  Timestamp: "Timestamp",
  Year2: "Year2",
  Year4: "Year4",
} as const;

export type ColumnType = (typeof ColumnType)[keyof typeof ColumnType];

export type ColumnTypeConfig = {
  type: ColumnType;
};
