export const ColumnType = {
  Char: "Char",
  CharN: "character(n)",
  VarCharN: "VarCharN",
  Text: "Text",
  TinyText: "TinyText",
  MediumText: "MediumText",
  LongText: "LongText",
  Int: "integer",
  IntN: "IntN",
  TinyInt: "TinyInt",
  TinyIntN: "TinyIntN",
  SmallInt: "SmallInt",
  SmallIntN: "SmallIntN",
  MediumInt: "MediumInt",
  MediumIntN: "MediumIntN",
  BigInt: "BigInt",
  BigIntN: "BigIntN",
  Date: "Date",
  Datetime: "Datetime",
  Boolean: "Boolean",
  Binary: "Binary",
  BinaryN: "BinaryN",
  VarBinaryN: "VarBinaryN",
  Bit1: "Bit1",
  BitN: "BitN",
  Blob: "Blob",
  TinyBlob: "TinyBlob",
  MediumBlob: "MediumBlob",
  LongBlob: "LongBlob",
  Decimal: "Decimal",
  DecimalP: "DecimalP",
  DecimalPS: "DecimalPS",
  Decimal104: "Decimal104",
  Decimal194: "Decimal194",
  Double: "Double",
  DoubleMD: "DoubleMD",
  Enum: "Enum",
  Float: "Float",
  FloatMD: "FloatMD",
  FloatP: "FloatP",
  Geometry: "Geometry",
  Json: "Json",
  Numeric: "Numeric",
  NumericP: "NumericP",
  NumericPS: "NumericPS",
  Real: "Real",
  RealMD: "RealMD",
  Set: "Set",
  Time: "Time",
  Timestamp: "Timestamp",
  Year2: "Year2",
  Year4: "Year4",
} as const;

export type ColumnType = (typeof ColumnType)[keyof typeof ColumnType];

export function parseColumnType(value: string): ColumnType | undefined {
  if ((Object.values(ColumnType) as string[]).includes(value)) {
    return value as ColumnType;
  }
  for (const key of Object.values(ColumnType)) {
    if (ColumnTypeConfigMap[key as ColumnType].label === value) {
      return key as ColumnType;
    }
  }
  return undefined;
}

export type ColumnTypeConfig = {
  label: string;
  labelWithoutArgs: string;
  supportsLength: boolean;
  supportsDecimal: boolean;
  supportsEnumArgs: boolean;
  supportsUnsigned: boolean;
};

export const ColumnTypeConfigMap: Record<ColumnType, ColumnTypeConfig> = {
  [ColumnType.Char]: {
    label: "char",
    labelWithoutArgs: "char",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.CharN]: {
    label: "char(n)",
    labelWithoutArgs: "char",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.VarCharN]: {
    label: "varchar(n)",
    labelWithoutArgs: "varchar",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Text]: {
    label: "text",
    labelWithoutArgs: "text",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.TinyText]: {
    label: "tinytext",
    labelWithoutArgs: "tinytext",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.MediumText]: {
    label: "mediumtext",
    labelWithoutArgs: "mediumtext",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.LongText]: {
    label: "longtext",
    labelWithoutArgs: "longtext",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Int]: {
    label: "int",
    labelWithoutArgs: "int",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.IntN]: {
    label: "int(n)",
    labelWithoutArgs: "int",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.TinyInt]: {
    label: "tinyint",
    labelWithoutArgs: "tinyint",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.TinyIntN]: {
    label: "tinyint(n)",
    labelWithoutArgs: "tinyint",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.SmallInt]: {
    label: "smallint",
    labelWithoutArgs: "smallint",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.SmallIntN]: {
    label: "smallint(n)",
    labelWithoutArgs: "smallint",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.MediumInt]: {
    label: "mediumint",
    labelWithoutArgs: "mediumint",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.MediumIntN]: {
    label: "mediumint(n)",
    labelWithoutArgs: "mediumint",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.BigInt]: {
    label: "bigint",
    labelWithoutArgs: "bigint",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.BigIntN]: {
    label: "bigint(n)",
    labelWithoutArgs: "bigint",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Date]: {
    label: "date",
    labelWithoutArgs: "date",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Datetime]: {
    label: "datetime",
    labelWithoutArgs: "datetime",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Boolean]: {
    label: "boolean",
    labelWithoutArgs: "boolean",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Binary]: {
    label: "binary",
    labelWithoutArgs: "binary",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.BinaryN]: {
    label: "binary(n)",
    labelWithoutArgs: "binary",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.VarBinaryN]: {
    label: "varbinary(n)",
    labelWithoutArgs: "varbinary",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Bit1]: {
    label: "bit(1)",
    labelWithoutArgs: "bit(1)",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.BitN]: {
    label: "bit(n)",
    labelWithoutArgs: "bit",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Blob]: {
    label: "blob",
    labelWithoutArgs: "blob",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.TinyBlob]: {
    label: "tinyblob",
    labelWithoutArgs: "tinyblob",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.MediumBlob]: {
    label: "mediumblob",
    labelWithoutArgs: "mediumblob",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.LongBlob]: {
    label: "longblob",
    labelWithoutArgs: "longblob",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Decimal]: {
    label: "decimal",
    labelWithoutArgs: "decimal",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.DecimalP]: {
    label: "decimal(p)",
    labelWithoutArgs: "decimal",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.DecimalPS]: {
    label: "decimal(p,s)",
    labelWithoutArgs: "decimal",
    supportsLength: true,
    supportsDecimal: true,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Decimal104]: {
    label: "decimal(10,4)",
    labelWithoutArgs: "decimal(10,4)",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Decimal194]: {
    label: "decimal(19,4)",
    labelWithoutArgs: "decimal(19,4)",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Double]: {
    label: "double",
    labelWithoutArgs: "double",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.DoubleMD]: {
    label: "double(m,d)",
    labelWithoutArgs: "double",
    supportsLength: true,
    supportsDecimal: true,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Enum]: {
    label: "enum",
    labelWithoutArgs: "enum",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: true,
    supportsUnsigned: false,
  },
  [ColumnType.Float]: {
    label: "float",
    labelWithoutArgs: "float",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.FloatMD]: {
    label: "float(m,d)",
    labelWithoutArgs: "float",
    supportsLength: true,
    supportsDecimal: true,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.FloatP]: {
    label: "float(p)",
    labelWithoutArgs: "float",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Geometry]: {
    label: "geometry",
    labelWithoutArgs: "geometry",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Json]: {
    label: "json",
    labelWithoutArgs: "json",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Numeric]: {
    label: "numeric",
    labelWithoutArgs: "numeric",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.NumericP]: {
    label: "numeric(p)",
    labelWithoutArgs: "numeric",
    supportsLength: true,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.NumericPS]: {
    label: "numeric(p,s)",
    labelWithoutArgs: "numeric",
    supportsLength: true,
    supportsDecimal: true,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Real]: {
    label: "real",
    labelWithoutArgs: "real",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.RealMD]: {
    label: "real(m,d)",
    labelWithoutArgs: "real",
    supportsLength: true,
    supportsDecimal: true,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Set]: {
    label: "set",
    labelWithoutArgs: "set",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Time]: {
    label: "time",
    labelWithoutArgs: "time",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Timestamp]: {
    label: "timestamp",
    labelWithoutArgs: "timestamp",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: false,
  },
  [ColumnType.Year2]: {
    label: "year(2)",
    labelWithoutArgs: "year(2)",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
  [ColumnType.Year4]: {
    label: "year(4)",
    labelWithoutArgs: "year(4)",
    supportsLength: false,
    supportsDecimal: false,
    supportsEnumArgs: false,
    supportsUnsigned: true,
  },
};
