import { type Settings, ViewMode } from "@/types/domain/settings";

export const defaultSettings: Settings = {
  database: "",
  capital: true,
  tableStyle: "",
  notation: "",
  notationLevel: 0,
  notationExpandGroup: true,
  viewMode: ViewMode.Logical,
  outlineViewMode: 1,
  viewOrderBy: 1,
  autoImeChange: false,
  validatePhysicalName: true,
  useBezierCurve: false,
  suspendValidator: false,
  titleFontEm: undefined,
  masterDataBasePath: undefined,
  useViewObject: false,
  exportSettings: {},
  categorySettings: {},
  modelProperties: {},
  tableProperties: {},
  environmentSettings: undefined,
  designSettings: undefined,
};
